name: python autotests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choise tests set
        required: true
        type: choose
        default: smoke
        options:
          - smoke
          - regression
          - all
    

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run autotests
    steps:
      - name: Checkout autotest
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
     
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        if: "github.event.inputs.deployment_target=='all'"
        run: pytest --alluredir=allure-results
        
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target=='smoke'"
        run: pytest -m smoke --alluredir=allure-results

      - name: Run regression tests
        if: "github.event.inputs.deployment_target=='regression'"
        run: pytest -m regression --alluredir=allure-results
     
      - name: install java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft' 
          java-version: '17'
      
      - name: Install Allure
        run: |
          wget --no-check-certificate https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.25.0/allure-commandline-2.25.0.zip
          unzip allure-commandline-*.zip -d allure
          echo "ALLURE_HOME=$(pwd)/allure" >> $GITHUB_ENV
          echo "$(pwd)/allure/bin" >> $GITHUB_PATH

      - name: Generate report
        run: allure generate allure-results --clean -o allure-report
      - name: save allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 1
      


      
