name: pythom autotests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run autotests
    steps:
      - name: Checkout autotest
        uses: actions/checkout@v5

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependenciecies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
